version: '3.1'

services:

  punch_clock:
    image: ghcr.io/altepizza/worklifebalance_bot:latest
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      context: punch_clock
      watch:
        - action: rebuild
          trigger: "./"
    environment:
      - DYNACONF_TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DYNACONF_CHAT_ID_WHITELIST=${CHAT_ID_WHITELIST}
      - DYNACONF_UPTIME_KUMA_URL=${UPTIME_KUMA_URL}
    volumes:
      - ./database:/app/database
